### ISSUE TITLE
Uncaught UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)


### ISSUE THREAD

**Issue by baditaflorin** [esc-unil/Visualist#10]
Couldn't load plugin 'visualist' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/__init__.py", line 39, in classFactory
    return VisualistPlugin(iface)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/visualist_main.py", line 87, in __init__
    yaml_document = yaml.safe_load(yaml_stream)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)

```
visualist 0.6, QGIS 3.14.16-Pi on Darwin 19.6.0

**Comment by bryanrscott** [comment]
same visualist 0.6, QGIS 3.20.0-Odense on OSX 11.4

**Comment by qrossy** [comment]
I will make some test on OSX, Did you try with QGIS 3.16.1 ? A new version of the plugin is in progress for QGis 3.16.x / 3.22
