### ISSUE TITLE
Attribute 'fromstring' issue in Spatial Autocorrelation Map

### ISSUE THREAD

**Issue by smuurling** [esc-unil/Visualist#12]
When I try to use the spatial autocorrelation map on a polygon I get this error message below. It used to work in the past (on an older version pf QGIS/pysal/python I believe).

I currently use QGIS 3.20.2, pysal 2.0.0 and python 3.10.

Any ideas on how to get it working again?

Traceback (most recent call last):
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\Lisa.py", line 177, in processAlgorithm
w = pysal.lib.weights.contiguity.Queen.from_shapefile(temp_file)
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\weights\contiguity.py", line 236, in from_shapefile
w = cls(FileIO(filepath), ids=ids, **kwargs)
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\weights\contiguity.py", line 182, in __init__
neighbors, ids = _build(polygons, ids=ids,
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\weights\contiguity.py", line 385, in _build
neighbor_data = ContiguityWeightsLists(polygons, wttype=wttype).w
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\weights\_contW_lists.py", line 53, in __init__
self.collection = list(collection)
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\io\fileio.py", line 254, in __next__
r = self.__read()
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\io\fileio.py", line 315, in __read
row = self._read()
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\io\iohandlers\pyShpIO.py", line 140, in _read
rec = self.dataObj.get_shape(self.pos)
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\io\util\shapefile.py", line 362, in get_shape
return self.shape.unpack(bufferIO(self.fileObj.read(byts)))
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\io\util\shapefile.py", line 636, in unpack
_unpackDict2(record, contentStruct, dat)
File "C:\Users/Sawna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\pysal\lib\io\util\shapefile.py", line 155, in _unpackDict2
result.fromstring(fileObj.read(result.itemsize * n))
AttributeError: 'array.array' object has no attribute 'fromstring'

**Comment by qrossy** [comment]
I have prepared a new version that should solve the problem. It will be put on the official repository after testing.
