### ISSUE TITLE
struct.error: unpack requires a buffer of 44 bytes

### ISSUE THREAD

**Issue by Marcoortiz22** [esc-unil/Visualist#13]
Hi, 
I'm trying to run a spatial autocorrelation but every time I tried i got the following error:

Versión de QGIS: 3.10.4-A Coruña
Versión de Qt: 5.12.8
Versión de GDAL: 3.0.4
Versión de GEOS: 3.8.0-CAPI-1.13.1 
Versión de PROJ: Rel. 6.3.1, February 10th, 2020
Procesando algoritmo...
Algoritmo 'Spatial Autocorrelation Map' comenzando…
Parámetros de entrada:
{ 'DISTANCE' : None, 'FIELD' : 'Total_deli', 'LISA' : 0, 'OUTPUT' : '/home/marco/Escritorio/Morans_I.gpkg', 'POLYGONS' : '/home/marco/Escritorio/Colonias_delitos/delitos_x_colonia.shp', 'W' : 0 }

Number of values of Y: 390997
Traceback (most recent call last):
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/Lisa.py", line 177, in processAlgorithm
w = pysal.lib.weights.contiguity.Queen.from_shapefile(temp_file)
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/weights/contiguity.py", line 236, in from_shapefile
w = cls(FileIO(filepath), ids=ids, **kwargs)
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/weights/contiguity.py", line 182, in __init__
neighbors, ids = _build(polygons, ids=ids,
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/weights/contiguity.py", line 385, in _build
neighbor_data = ContiguityWeightsLists(polygons, wttype=wttype).w
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/weights/_contW_lists.py", line 53, in __init__
self.collection = list(collection)
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/io/fileio.py", line 254, in __next__
r = self.__read()
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/io/fileio.py", line 315, in __read
row = self._read()
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/io/iohandlers/pyShpIO.py", line 140, in _read
rec = self.dataObj.get_shape(self.pos)
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/io/util/shapefile.py", line 362, in get_shape
return self.shape.unpack(bufferIO(self.fileObj.read(byts)))
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/io/util/shapefile.py", line 633, in unpack
record = _unpackDict(cls.USTRUCT, dat)
File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/io/util/shapefile.py", line 138, in _unpackDict
items = unpack(struct['order'] + struct['fmt'],
struct.error: unpack requires a buffer of 44 bytes

La ejecución falló después de 44.54 segundos

Cargando las capas resultantes
Algoritmo 'Spatial Autocorrelation Map' finalizado

Hope you can help me to solve this problem.

Cheers,

Marco

**Comment by qrossy** [comment]
You may try the version [0.7](https://plugins.qgis.org/plugins/visualist/version/0.7/) with qGis 3.22 ... this may solve the issue ?

**Comment by Marcoortiz22** [comment]
Not really. I installed QGIS 3.22 and visualist version 0.7 in a fresh install of Manjaro Linux (KDE version). However, everytime I launche QGIS with the plugin activated QGIS died. 


I got the message after the following steps:
first attemp to activate visualist plugin I got a warning of missing scipy, so I did pip install scify
Then missing pandas, so I did pip install pandas
The next warning was about shapely, so I did pip install shapely
After succesfully installed I got the following message in terminal:

Warning: link #path2410 is undefined!
Warning: link #path2410 is undefined!
Warning: link #path2410 is undefined!
Warning: QString::arg: Argument missing: Shapefiles, *.shp *.SHP
<string>:1: DeprecationWarning: setapi() is deprecated
QGIS died on signal 11zsh: IOT instruction (core dumped)  qgis

Any idea?

**Comment by qrossy** [comment]
Thank you for the feedback, it works with the LTR version on windows and osx. I did not try on linux. I'll try to do so, as soon as I can.
