### ISSUE TITLE
Error to activate plug

### ISSUE THREAD

**Issue by bellanz80** [esc-unil/Visualist#14]
Hi.
The plugin is great.
But since some versions I can't install and use it.
I always get the same python error, regardless of whether it is a new profile or already with several plugs installed.

ModuleNotFoundError: No module named 'processing.core.ProcessingLog' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python/plugins\visualist\__init__.py", line 37, in classFactory
    from .visualist_main import VisualistPlugin
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python/plugins\visualist\visualist_main.py", line 41, in 
    from .visualist_provider import VisualistProvider
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python/plugins\visualist\visualist_provider.py", line 42, in 
    from .EdgesToFlow import EdgesToFlow
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python/plugins\visualist\EdgesToFlow.py", line 53, in 
    from .edgebundlingUtils import Edge, EdgeCluster
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python/plugins\visualist\edgebundlingUtils.py", line 37, in 
    from processing.core.ProcessingLog import ProcessingLog
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing.core.ProcessingLog'

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdada 

Ruta de Python:
C:/OSGeo4W/apps/qgis/./python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages\win32
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages\win32\lib
C:\Users\Luca\AppData\Roaming\Python\Python39\site-packages\Pythonwin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\new/python

Win 10
QGIS 3.26.3
QGIS 3.22

![image](https://user-images.githubusercontent.com/38449926/189969862-8f64c03b-9510-45f6-aad2-db63c601fc54.png)

**Comment by qrossy** [comment]
Thank you for the feedback, it works with the LTR version. I'll try to check for qGIS 3.26.3 ASAP.

**Comment by qrossy** [comment]
Corrected, new version to come in the official repop

**Comment by bellanz80** [comment]
> 

Very thenak`s!!!
