### ISSUE TITLE
cannot import name 'inf' from 'scipy' 

### ISSUE THREAD

**Issue by smblnts21** [esc-unil/Visualist#15]
ImportError: cannot import name 'inf' from 'scipy' (/usr/lib/python3.11/site-packages/scipy/__init__.py) 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/__init__.py", line 37, in classFactory
    from .visualist_main import VisualistPlugin
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/visualist/visualist_main.py", line 41, in 
    from .visualist_provider import VisualistProvider
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)

**Comment by smblnts21** [comment]
ModuleNotFoundError: No module named 'scipy' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/__init__.py", line 37, in classFactory
    from .visualist_main import VisualistPlugin
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/visualist_main.py", line 41, in 
    from .visualist_provider import VisualistProvider
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/visualist_provider.py", line 43, in 
    from .Lisa import LocalIndicatorSpatialA
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/Lisa.py", line 34, in 
    from . import pysal
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/__init__.py", line 57, in 
    from . import lib
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/__init__.py", line 23, in 
    from . import cg
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/cg/__init__.py", line 4, in 
    from .shapes import *
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/cg/shapes.py", line 9, in 
    from .sphere import arcdist
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexander/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/cg/sphere.py", line 19, in 
    import scipy.spatial
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'


Python version: 3.9.18 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0] 
QGIS version: 3.28.9-Firenze Firenze

**Comment by qrossy** [comment]
Thank you for the feedback, I'll try to find a solution

**Comment by qrossy** [comment]
A new version 0.8.1 has been submited to the QGIS repository: should work on QGIS 3.34.7 LTR

**Comment by smblnts21** [comment]
Gracias me gustaría probarla, aunque todavía no está subida a los complementos del QGIS

**Comment by smblnts21** [comment]
Ya lo subieron, excelente funciona bien hasta donde la he probado, muchas gracias por tomarse el tiempo de corregirla
