### ISSUE TITLE
Error on update QGIS 3.14.15

### ISSUE THREAD

**Issue by bellanz80** [esc-unil/Visualist#8]
Hi, i update QGIS on 3.14.15 and the plug doasn't work..

Couldn't load plugin 'visualist' 

ImportError: DLL load failed: No se puede encontrar el módulo especificado. 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\__init__.py", line 28, in 
    from .visualist_main import VisualistPlugin
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\visualist_main.py", line 41, in 
    from .visualist_provider import VisualistProvider
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\visualist_provider.py", line 43, in 
    from .Lisa import LocalIndicatorSpatialA
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\Lisa.py", line 34, in 
    from visualist import pysal
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\pysal\__init__.py", line 2, in 
    from . import lib
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\pysal\lib\__init__.py", line 27, in 
    from . import cg
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\pysal\lib\cg\__init__.py", line 4, in 
    from .shapes import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\pysal\lib\cg\shapes.py", line 9, in 
    from .sphere import arcdist
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\pysal\lib\cg\sphere.py", line 15, in 
    import scipy.spatial
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scipy\spatial\__init__.py", line 102, in 
    from ._procrustes import procrustes
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scipy\spatial\_procrustes.py", line 11, in 
    from scipy.linalg import orthogonal_procrustes
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scipy\linalg\__init__.py", line 195, in 
    from .misc import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scipy\linalg\misc.py", line 5, in 
    from .blas import get_blas_funcs
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scipy\linalg\blas.py", line 215, in 
    from scipy.linalg import _fblas
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.15-Pi Pi, d5114d2cfa 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\GlobeBuilder
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\GroupPointsWithinDistance
C:\Users\Luca\AppData\Roaming\QGIS\QGIS3\profiles\LUCA1\python\plugins\mmqgis/forms
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\qgis2web
C:\Users\Luca\AppData\Roaming\QGIS\QGIS3\profiles\LUCA1\python\plugins
C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\qgis_resource_sharing
C:\Users\Luca\AppData\Roaming\QGIS\QGIS3\profiles\LUCA1\python\plugins\qgis_resource_sharing
C:\Users\Luca\AppData\Roaming\QGIS\QGIS3\profiles\LUCA1\python\plugins\qgis_resource_sharing\ext_libs

**Comment by qrossy** [comment]
The bug is outside the plugin... I've no idea how to fix it right now. You should try with the LTR version

**Comment by bellanz80** [comment]
Thank you very much. I had a lot of errors with the OSGEO installation.
I went to standalone 3.14 (first version) and the plug works without problems.
Thank you very much!
