### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'scipy'


### ISSUE THREAD

**Issue by baditaflorin** [esc-unil/Visualist#9]
Couldn't load plugin 'visualist'
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/__init__.py", line 28, in <module>
    from .visualist_main import VisualistPlugin
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/visualist_main.py", line 41, in <module>
    from .visualist_provider import VisualistProvider
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/visualist_provider.py", line 43, in <module>
    from .Lisa import LocalIndicatorSpatialA
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/Lisa.py", line 34, in <module>
    from visualist import pysal
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/__init__.py", line 2, in <module>
    from . import lib
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/__init__.py", line 27, in <module>
    from . import cg
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/cg/__init__.py", line 4, in <module>
    from .shapes import *
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/cg/shapes.py", line 9, in <module>
    from .sphere import arcdist
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/visualist/pysal/lib/cg/sphere.py", line 15, in <module>
    import scipy.spatial
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'

```
visualist 0.6, QGIS 3.14.16-Pi on Darwin 19.6.0

**Comment by qrossy** [comment]
Did you try with QGIS 3.16.1 ? A new version of the plugin is in progress for QGis 3.16.x / 3.22
